spring:
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: http://localhost:8080
          predicates:
            - Path=/my-service/**
          filters:
            - name: RequestRateLimiter
              args:
                custom-rate-limiter.replenishRate: 10
                custom-rate-limiter.burstCapacity: 20
      ratelimiter:
        key-resolver: apiKeyResolver
        custom-rate-limiter:
          enabled: true

server:
  port: 9090